### ISSUE TITLE
Installation Lab

### ISSUE THREAD

**Issue by AleNegrini** [AleNegrini/SEBC#1]

**Comment by AleNegrini** [comment]
Installation Lab **started**

**Comment by AleNegrini** [comment]
Installation Lab **completed**

**Comment by AleNegrini** [comment]
MariaDB in HA installation **started**

**Comment by AleNegrini** [comment]
MariaDB in HA installation **completed**

**Comment by AleNegrini** [comment]
Cloudera Manager installation **started**

**Comment by AleNegrini** [comment]
Cloudera Manager installation **completed**

**Comment by AleNegrini** [comment]
Bonus lab **started**

**Comment by AleNegrini** [comment]
Bonus lab **completed**

**Comment by cfusi** [comment]
The lab is correct.

Two notes:
- In Centos 7 the firewall process is `firewalld`, so check that this is off and disabled
- After adding a local repo, you should show that it is listed as a valid parcel in the CM parcel list
