### ISSUE TITLE
Storage labs

### ISSUE THREAD

**Issue by AleNegrini** [AleNegrini/SEBC#2]

**Comment by AleNegrini** [comment]
Replication to another cluster **started**

**Comment by AleNegrini** [comment]
Replication to another cluster **completed**

**Comment by AleNegrini** [comment]
HDFS Throughput **started**

**Comment by AleNegrini** [comment]
Test HDFS throughput **completed**

**Comment by AleNegrini** [comment]
Test HDFS Snapshots **started**

**Comment by AleNegrini** [comment]
Test HDFS Snapshots **completed**

**Comment by AleNegrini** [comment]
NameNode in HA **started**

**Comment by AleNegrini** [comment]
NameNode in HA **completed**

**Comment by AleNegrini** [comment]
Cloudera Manager URL:
[http://104.196.167.212:7180]

**Comment by cfusi** [comment]
That's OK
